name: "autotools CI"
on: 
  push:
    branches:
      - main 
      - master
  pull_request:
    branches: 
      - '*'
jobs:
  macOS:
    name: Build on  macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: ./build_and_install.sh ~/.local
      - name: Test
        run: |
            ls ~/.local/bin
            ls ~/.local/lib
